<?php

namespace App\Http\Livewire\Pages;

use App\Services\Ark\ArkExplorer;
use Livewire\Component;

class BlocksShow extends Component
{
    const ROWS = [
        'transactions' => 'Transactions',
        'confirmations' => 'Confirmations',
        'height' => 'Height',
        'reward' => 'Reward',
        'fee' => 'Fees',
        'total' => 'Total forged',
        'amount' => 'Process amount',
        'timestamp' => 'Timestamp',
        'generator' => 'Generated By',
    ];

    protected $block;
    public $actions;
    public $rows;
    
    public function mount()
    {
        $block = ArkExplorer::getBlock(request()->id)->json('data');
        $lastBlock = ArkExplorer::getLastBlock()->json('data');

        $actions[] = [
            'url' => route('blocks.show', ['id' => $block['height'] - 1]),
            'label' => '← Previous block',
            'variant' => 'secondary',
        ];
        
        if ($block['height'] + 1 < $lastBlock['height']) {
            $actions[] = [
                'url' => route('blocks.show', ['id' => $block['height'] + 1]),
                'label' => 'Next block →',
                'variant' => 'secondary',
            ];
        }
            
        $this->actions = $actions;
        $this->block = $block;
        $this->rows = self::ROWS;
    }

    public function render()
    {
        return view('livewire.pages.blocks.show', [
            'block' => $this->block
        ])->layout('layouts.guest');
    }
}
